sudo: required
services:
  - docker
before_install:
  - docker build -f Dockerfile.dev -t scottcollins/react-webapp:test .
script:
  - docker run scottcollins/react-webapp:test npm run test -- --coverage
